### PR TITLE
Fixed #67: Create roster API and set up teamNavigator

### LINKED ISSUE #67: Improve discoverability on the home page
I'm seeing nearly a 50% dropoff on the front page of baseballmod.com. That's pretty crazy that 1/2 the visitors would come to the site and not look at a player page.

I think there are two problems....

1) the "find a player" input box isn't obvious
2) the visitor has to type to get somewhere, which is a lot to ask a first time visitor

We can do a couple things to improve this. Immediately, maybe we just make the search box more obvious with a simple animation like this:
http://screencast.com/t/Zy8AqLiZJg4

I'm not in love with that though. I think animations aren't to be used lightly.

Another thing we could do is to offer a couple more sections before the fold on the first page. Something like..
- hot performers - clickable images and names here would go a long way for ease of use
- team links and pages - showing the most recent roster for each page when clicked.

I'm leaving this open as a discussion for now until I feel we're ready for some dev on it.

### PR DESCRIPTION
**Pull request by albertlyu**
@kruser, here are the new teamNavigator files on the front page. You may want to finalize how you want the front page to look. I added animate.css to the select team and players, as you'll see in teamNavigator.html. Let me know if you have any questions about this.

### CODE REVIEW

**Comment by kruser** [comment]
Looks functional. Good job prepping for minification/production too. I'm going to change a few visuals but all-in-all it looks great. I'll probably push to the site later tonight.

**Comment by albertlyu** [comment]
Note that I made some small changes, such as allowing the GitHub ribbon to show for md screen sizes, shortened the input form on the nav bar so that sm screens look a little better too, added #about link for the main home page. Those are the ones that came to the top of my head, there might be a couple more though.

**Comment by kruser** [comment]
@albertlyu, I modified just a few minor things.
- added `btn-block` to the team buttons
- created a `playerButton` directive and juggled the markup a tad. This directive allowed me to do it in one place
- I had to move the initial animation to a slideRight since when you click the About link from an outside page the fadeInUp caused some funkiness.

Other than that I shuffled some bootstrap markup around a tad to make sure rows weren't there were needed and things generally lined up, like always adding columns up to 12. See my commits after yours if you're curious.

So give it a look on the homepage and let me know if there is anything else you'd like to do before I tweet it out.

**Comment by albertlyu** [comment]
Looks great on the site - thanks for cleaning up after me!

**Pull request closed without merging**
