### PR TITLE
Added some padding to the team and player buttons to improve mobile UX

### PR DESCRIPTION
**Pull request by albertlyu**
As discussed on Twitter... per @kruser's approval.

### CODE REVIEW

**Comment by kruser** [comment]
I think this might be too much of a band-aid fix, just adding a little bit of padding. We could revert to a <select> for xs screens instead, similar to how we do the picker for heatmaps.

**Comment by albertlyu** [comment]
Sounds good -- it definitely is not too much of a pressing issue, mostly just aesthetics, as I'm thinking of the mobile user experience for when I go to the ballpark this weekend. I'm also thinking on the homepage, the href property is a little unnecessary as that refreshes the page. Perhaps scroll the page all the way back to the top, so changing it from `href="/"` to `href="#"`.
https://github.com/kruser/pitchfx-site/blob/master/app/app/views/index.html#L23

Definitely though, there are bigger fish to fry :)

**Comment by albertlyu** [comment]
I'm going to close this pull request so that I can make changes to my repo without affecting this pull request.

**Comment by kruser** [comment]
I think if we just used the team names here we wouldn't have an issue.

**Comment by kruser** [comment]
BTW, the problem is much more pronounced in iPhone.

**Comment by albertlyu** [comment]
Ahh okay. So something like this?...:

``` html
<button type="button" class="btn btn-default btn-block btn-lg default" ng-click="openTeam(team)"><span class="hidden-xs">{{team.display}}</span><span class="visible-xs">{{team.name}}</span></button>
```

https://github.com/kruser/pitchfx-site/blob/master/app/app/views/partials/teamNavigator.html#L4

**Comment by kruser** [comment]
Just team names all around.
- Cubs
- Twins
- Yankees
- etc.

Why not?

**Comment by albertlyu** [comment]
Ahh right. One potential issue I do is that in the `roster.js` controller, where we hard-coded the team names, we also explicitly sorted them in alphabetical order of `team.display`. In adding team nicknames to accommodate the mobile views, we'd probably have to use the team nicknames for the desktop and tablet views too, which I have no problem with, just something to keep in mind. For instance, if we wanted to display 'Cubs' for mobile, and 'Chicago Cubs' for everything else, we'd have to keep the same order of teams for all the views.

**Comment by kruser** [comment]
Do the sort in the UI.

Something like...
  ng-repeat="team in teams | orderBy:'nickname'"

I wouldn't try to do things differently in the mobile view vs large either.
I would just use the nickname on all.

**Comment by kruser** [comment]
I just hid the 'btn-lg' on xs screens in favor of a regular button. Looks much better and I didn't have to do anything unnatural.

**Pull request closed without merging**
