### PR TITLE
fixed #54: add new wOBA/BIP, BABIP and BIP rate zone charts

### LINKED ISSUE #54: New Zone Charts - BABIP, wOBA, etc.
I'd like to add some new heatmaps to the zone charts we already have. Here is what exists...
image

For this issue, I'd like to add..
- wOBA
- BABIP
- BIP

I'll leave this unassigned for now. If anybody is interested in adding these I can walk you through the heatmaps framework I setup for the others.

### PR DESCRIPTION
**Pull request by albertlyu**
As promised, a pull request for @kruser to review -- pending karma tests on the new functions. I went with 0.400 for both wOBA/BIP and BABIP, and 0.500 for BIP rate. Perhaps the red heat painting for BIP rate should be lower. I'll leave that up to @kruser's discretion. Later, I may take a look at BIP/Swing and HR/BIP or HR/FB or HR/non-GB (not sure what you'd call the latter).

### CODE REVIEW

**Comment by kruser** [comment]
This looks good, and it passes the Travis CI build too! 

Please add a karma test for each of the three charts and then we'll get this out on the site. This will make it so nobody else breaks your calculations going forward.

**Comment by albertlyu** [comment]
Sounds good. I believe if I push the karma test code changes to my repo, it'll show up in this pull request as an additional commit.

**Comment by albertlyu** [comment]
Alright, karma tests have been added for IsHomeRun() and each of the three charts. Did some pen and paper calculations to make sure I'm getting the values I want for the test pitches to Josmil Pinto. Hopefully the Travis CI build passes. By the way, I wasn't able to run grunt jsbeautify from the app directory. I'll have to figure out why at some point, but I was careful in making sure my added code matched the format of other code.

**Comment by albertlyu** [comment]
I have a habit of `git add .` when setting up my `git commit`s. Wondering why those two svg files always get tagged as modified files when they're not?

**Comment by kruser** [comment]
I wonder if git has some rules for svgs. You're on windows, right? I'm on a
Mac so we certainly might have some differences due to those. I would just
hope the git client would do the right thing.

**Comment by albertlyu** [comment]
Yup I'm on Windows. Next time, I won't `git add .` then, or at least, I can make sure I untrack those svg files before committing.

**Comment by kruser** [comment]
FYI, the beautify command is..

```
grunt jsbeautifier
```

I'm updating the developer guide now.

all of your modifications were already beautiful - no changes from grunt.

**Pull request merged**
