### PR TITLE
fixed #59: restored whiff% in pitchStats.js, also beautify

### LINKED ISSUE #59: Whiff % is showing 0% for all pitches
Ughh

image

### PR DESCRIPTION
**Pull request by albertlyu**
File changes for bbm credits are due to jsbeautifier.

### CODE REVIEW

**Comment by kruser** [comment]
The jshint step on the build is broken on this pull request. Let me try to manually pull these things in. Thanks for identifying the error

**Comment by kruser** [comment]
I reorg'd the original code a little bit so it would pass my jshint rules and committed a separate fix. I don't want to relax those rules even for one-offs like this. Thanks for fixing my bug @albertlyu!

**Comment by albertlyu** [comment]
Great! Additionally, we could have moved the `/* jshint maxdepth:5 */` option so that it precedes the `isSwing()` and `isWhiff()` checks. Not sure what best practice is there in terms of what is more optimal, but I figured that would pass the jshint step in the Travis BI build if so.

**Comment by kruser** [comment]
Yep, you're right that it would have passed with that comment. Technically that would be a few instructions faster too, but nothing I'm worried about since we're dealing with hundreds of things, not millions.

**Pull request closed without merging**
